const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const WebSocket=require('ws');
const {Pool}=require('pg');
const PORT=process.env.PORT||3000,ROOT=__dirname;
const DATABASE_URL=String(process.env.DATABASE_URL||'').trim();
const pgPool=DATABASE_URL?new Pool({connectionString:DATABASE_URL,max:5,idleTimeoutMillis:30000,connectionTimeoutMillis:10000}):null;
const rooms=new Map(),alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const DB_FILE=path.join(ROOT,'players.json');const ANNOUNCEMENT_FILE=path.join(ROOT,'announcement.json');const SUPPORT_FILE=path.join(ROOT,'support_tickets.json');const RESET_FILE=path.join(ROOT,'password_reset_requests.json');
let announcement={enabled:false,text:'',updatedAt:null};
try{announcement=Object.assign(announcement,JSON.parse(fs.readFileSync(ANNOUNCEMENT_FILE,'utf8')||'{}'))}catch{}
function saveAnnouncement(){try{fs.writeFileSync(ANNOUNCEMENT_FILE,JSON.stringify(announcement,null,2))}catch{}}
let supportTickets=[];try{supportTickets=JSON.parse(fs.readFileSync(SUPPORT_FILE,'utf8')||'[]')}catch{}
function saveSupport(){try{fs.writeFileSync(SUPPORT_FILE,JSON.stringify(supportTickets,null,2))}catch{}}
let resetRequests=[];try{resetRequests=JSON.parse(fs.readFileSync(RESET_FILE,'utf8')||'[]')}catch{}
function saveResets(){try{fs.writeFileSync(RESET_FILE,JSON.stringify(resetRequests,null,2))}catch{}}

let accounts={}; try{accounts=JSON.parse(fs.readFileSync(DB_FILE,'utf8')||'{}')}catch{}
const sessions=new Map();
const adminSessions=new Map();
const ANALYTICS_FILE=path.join(ROOT,'analytics.json');
let analytics={visits:0,uniqueVisitors:0,daily:{}};
try{analytics=Object.assign(analytics,JSON.parse(fs.readFileSync(ANALYTICS_FILE,'utf8')||'{}'))}catch{}
const saveAnalytics=()=>{try{fs.writeFileSync(ANALYTICS_FILE,JSON.stringify(analytics,null,2))}catch{}};
const visitorIds=new Set();
const hash=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
const validId=v=>{v=String(v||'').trim().toLowerCase(); return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)||/^[+]?[- 0-9]{8,18}$/.test(v)};
const validGameId=v=>/^[A-Za-z0-9_]{3,20}$/.test(String(v||'').trim());
const gameIdTaken=v=>Object.values(accounts).some(a=>String(a.gameId||'').toLowerCase()===String(v||'').toLowerCase());
const accountForLogin=v=>{const q=String(v||'').trim().toLowerCase();if(!q)return null;return accounts[q]||Object.values(accounts).find(a=>String(a.gameId||'').trim().toLowerCase()===q)||null};
let persistChain=Promise.resolve();
const saveAccounts=()=>{
  try{fs.writeFileSync(DB_FILE,JSON.stringify(accounts,null,2))}catch{}
  if(!pgPool)return;
  const snapshot=Object.values(accounts).map(a=>({identifier:String(a.identifier||'').trim().toLowerCase(),data:a})).filter(x=>x.identifier);
  persistChain=persistChain.then(async()=>{
    const client=await pgPool.connect();
    try{
      await client.query('BEGIN');
      for(const row of snapshot){
        await client.query('INSERT INTO accounts(identifier,data,updated_at) VALUES($1,$2::jsonb,NOW()) ON CONFLICT(identifier) DO UPDATE SET data=EXCLUDED.data,updated_at=NOW()',[row.identifier,JSON.stringify(row.data)]);
      }
      await client.query('COMMIT');
    }catch(e){try{await client.query('ROLLBACK')}catch{};console.error('PostgreSQL account save failed:',e.message)}
    finally{client.release()}
  }).catch(e=>console.error('PostgreSQL persistence queue failed:',e.message));
};
async function initAccountPersistence(){
  if(!pgPool){console.warn('DATABASE_URL not configured; using local players.json storage.');return 'file';}
  const client=await pgPool.connect();
  try{
    await client.query('CREATE TABLE IF NOT EXISTS accounts (identifier TEXT PRIMARY KEY, data JSONB NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())');
    const result=await client.query('SELECT identifier,data FROM accounts ORDER BY identifier');
    if(result.rows.length){
      const restored={};
      for(const row of result.rows){
        try{restored[String(row.identifier).toLowerCase()]=typeof row.data==='string'?JSON.parse(row.data):row.data}catch(e){console.error('Skipping invalid PostgreSQL account row:',row.identifier)}
      }
      accounts=restored;
      try{fs.writeFileSync(DB_FILE,JSON.stringify(accounts,null,2))}catch{}
      console.log(`PostgreSQL persistence loaded ${Object.keys(accounts).length} account(s).`);
    }else if(Object.keys(accounts).length){
      for(const a of Object.values(accounts)){
        const identifier=String(a.identifier||'').trim().toLowerCase();
        if(identifier)await client.query('INSERT INTO accounts(identifier,data,updated_at) VALUES($1,$2::jsonb,NOW()) ON CONFLICT(identifier) DO UPDATE SET data=EXCLUDED.data,updated_at=NOW()',[identifier,JSON.stringify(a)]);
      }
      console.log(`Migrated ${Object.keys(accounts).length} local account(s) into PostgreSQL.`);
    }else{
      console.log('PostgreSQL account store is empty; ready for new registrations.');
    }
    return 'postgres';
  }finally{client.release()}
}
const token=()=>crypto.randomBytes(24).toString('hex');
const auth=t=>{const pid=sessions.get(String(t||''));return pid?accountForPlayerId(pid):null};
const ownerGameId=()=>String(process.env.OWNER_GAME_ID||'').trim();
const ownerEmail=()=>String(process.env.OWNER_EMAIL||'').trim().toLowerCase();
const adminTeamIds=()=>String(process.env.ADMIN_TEAM_IDS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);
const adminPin=()=>String(process.env.ADMIN_PIN||'').trim()||fileAdminPin();
const ADMIN_TEAM_FILE=path.join(ROOT,'admin_team.json');
let adminTeamFile={ownerGameId:'',teamIds:[],pin:'',pinHash:''};
try{adminTeamFile=Object.assign(adminTeamFile,JSON.parse(fs.readFileSync(ADMIN_TEAM_FILE,'utf8')||'{}'))}catch{}
const fileOwnerGameId=()=>String(adminTeamFile.ownerGameId||'').trim();
const fileAdminTeamIds=()=>Array.isArray(adminTeamFile.teamIds)?adminTeamFile.teamIds.map(x=>String(x||'').trim().toLowerCase()).filter(Boolean):[];
const fileAdminPin=()=>String(adminTeamFile.pin||'').trim();
const ownerRecoveryPin=()=>String(process.env.OWNER_RECOVERY_PIN||'').trim()||String(adminTeamFile.ownerRecoveryPin||'').trim()||fileAdminPin();
const adminPasswordHash=()=>String(adminTeamFile.pinHash||'').trim() || (adminPin()?hash(adminPin()):'');
const isOwnerAccount=acc=>{if(!acc)return false;const g=String(acc.gameId||'').trim().toLowerCase();return String(acc.role||'').toUpperCase()==='OWNER'||(ownerGameId()&&g===ownerGameId().toLowerCase())||(fileOwnerGameId()&&g===fileOwnerGameId().toLowerCase())||(ownerEmail()&&String(acc.identifier||'').toLowerCase()===ownerEmail())};
const adminPasswordMatches=p=>{const expected=adminPasswordHash();return !!expected&&hash(p)===expected};
const saveAdminTeam=()=>{try{fs.writeFileSync(ADMIN_TEAM_FILE,JSON.stringify(adminTeamFile,null,2))}catch{}};
const adminToken=()=>crypto.randomBytes(18).toString('hex');
const adminAllowedGameId=gid=>{const g=String(gid||'').trim().toLowerCase();return !!g&&(g===ownerGameId().toLowerCase()||adminTeamIds().includes(g)||g===fileOwnerGameId().toLowerCase()||fileAdminTeamIds().includes(g));};
const adminAllowedAccount=acc=>{if(!acc)return false;const g=String(acc.gameId||'').trim().toLowerCase();return String(acc.role||'').toUpperCase()==='OWNER'||String(acc.role||'').toUpperCase()==='ADMIN'||adminAllowedGameId(g);};
const subscriptionState=acc=>{
  if(!acc) return {plan:'FREE',status:'FREE',premium:false,source:'NONE',expiresAt:null};
  if(String(acc.role||'').toUpperCase()==='OWNER' || (ownerGameId() && String(acc.gameId||'').toLowerCase()===ownerGameId().toLowerCase()) || (ownerEmail() && String(acc.identifier||'').toLowerCase()===ownerEmail())) return {plan:'OWNER_PREMIUM',status:'ACTIVE',premium:true,source:'OWNER',expiresAt:null};
  const sub=acc.subscription||{};
  if(sub.expiresAt && Number(sub.expiresAt)<=Date.now() && sub.status==='ACTIVE'){ sub.status='EXPIRED'; sub.plan='FREE'; sub.premium=false; sub.source='EXPIRED'; saveAccounts(); }
  if(sub.status==='ACTIVE' && sub.expiresAt && Number(sub.expiresAt)>Date.now()) return {...sub,premium:true};
  return {plan:'FREE',status:sub.status==='EXPIRED'?'EXPIRED':'FREE',premium:false,source:sub.source||'NONE',expiresAt:sub.expiresAt||null};
};
const accountForPlayerId=pid=>Object.values(accounts).find(a=>a.playerId===pid);
const requireAdmin=req=>{const t=String(req.headers['x-admin-session']||'');return !!t&&adminSessions.has(t)};
const saveAndReturnAccount=(acc)=>{acc.subscription=subscriptionState(acc);saveAccounts();return acc};
const id=()=>Math.random().toString(36).slice(2,10);
const code=()=>{let c='';do{for(let i=0;i<6;i++)c+=alphabet[Math.floor(Math.random()*alphabet.length)]}while(rooms.has(c));return c};
const teamPlayers=(r,t)=>r.players.filter(p=>p.team===t);
const safeText=(v,n)=>String(v||'').replace(/[<>]/g,'').slice(0,n);
const hostOf=r=>r.players.find(p=>p.id===r.roomAdminId && p.online!==false)||r.players.find(p=>p.online!==false)||r.players[0];
const onlinePlayers=r=>r.players.filter(p=>p.online!==false);
const authorityLevel=(r,p)=>{if(!p)return 0;if(r.roomAdminId===p.id)return 5;if(isCaptain(r,p))return 4;if(isReferee(r,p))return 3;if(r.officialIds?.has(p.id))return 3;if(r.commentatorId===p.id)return 3;return 0};
const canManage=(r,p)=>authorityLevel(r,p)>=3;
const sendTeam=(r,team,o)=>r.players.filter(p=>p.team===team&&p.online!==false).forEach(p=>send(p.ws,o));
const sendVoice=(r,from,scope,data)=>{if(scope==='team')sendTeam(r,from.team,{type:'voice',name:from.name,team:from.team,scope,data,at:Date.now()});else broadcast(r,{type:'voice',name:from.name,team:from.team,scope,data,at:Date.now()});};
function assignCaptains(r){ for(const t of ['A','B']){ if(!r.captains) r.captains={A:null,B:null}; if(!r.captains[t]){ const v=r.viceCaptains?.[t]; const q=r.players.find(p=>p.id===v&&p.team===t); if(q) r.captains[t]=q.id; else { const first=r.players.find(p=>p.team===t&&p.role==null); if(first) r.captains[t]=first.id; } } } }
function isCaptain(r,p){assignCaptains(r);return !!p && (r.captains.A===p.id||r.captains.B===p.id)}
function isReferee(r,p){return !!p && (r.refereeId===p.id || (!r.refereeId && hostOf(r)?.id===p.id));}
const maxWickets=r=>Math.max(1,Math.min(10,teamPlayers(r,r.battingTeam).length-1));
const isPremiumAccount=acc=>!!subscriptionState(acc).premium;
function publicState(r,viewer){
 const bat=teamPlayers(r,r.battingTeam), bowl=teamPlayers(r,r.bowlingTeam);
 const activeBat=bat[r.batterPos%Math.max(1,bat.length)],activeBowl=bowl[r.bowlerPos%Math.max(1,bowl.length)];
 return {room:r.code,matchType:r.matchType||'limited',overs:r.overs||5,names:r.players.map(p=>p.name),players:r.players.map(p=>({id:p.id,name:p.name,team:p.team,ready:p.ready,online:p.online!==false,role:p.role||'player',captain:!p.role&&r.captains?.[p.team]===p.id})),teamNames:r.teamNames||{A:'Team A',B:'Team B'},roles:{refereeId:r.refereeId||null,commentatorId:r.commentatorId||null,officialIds:[...r.officialIds||[]]},roomCreatorId:r.roomAdminId||r.players[0]?.id||null,roomAdminId:r.roomAdminId||null,innings:r.innings,score:r.score,wickets:r.wickets,balls:r.balls,target:r.target,gameOver:r.gameOver,commentary:r.commentary,submitted:r.choices.has(viewer),lockedUntil:r.lockedUntil||0,phase:r.phase,turnPlayers:[activeBat?.id,activeBowl?.id].filter(Boolean),activeBatter:activeBat?.name||'',activeBowler:activeBowl?.name||'',activeBatterId:activeBat?.id||null,activeBowlerId:activeBowl?.id||null,battingTeam:r.battingTeam,bowlingTeam:r.bowlingTeam,firstInnings:r.firstInnings,toss:r.toss,tossWinner:r.tossWinner,decision:r.decision,ballHistory:r.ballHistory||[],inningsHistory:r.inningsHistory||[],playerStats:r.playerStats||{},mom:r.mom||null};
}
function send(ws,o){if(ws&&ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(o))}
function broadcast(r,o){r.players.forEach(p=>send(p.ws,o))}
function broadcastState(r){r.players.forEach(p=>send(p.ws,{type:'state',state:publicState(r,p.id)}))}
function roomInfo(r){assignCaptains(r);return {type:'room',room:r.code,access:r.access||'free',matchType:r.matchType||'limited',overs:r.overs||5,playerId:null,host:r.roomAdminId||r.players[0]?.id,players:r.players.filter(p=>!p.role).length,readyCount:r.players.filter(p=>!p.role&&p.ready).length,names:r.players.map(p=>p.name),playerList:r.players.map(p=>({id:p.id,name:p.name,team:p.team,ready:p.ready,online:p.online!==false,role:p.role||'player',captain:!p.role&&r.captains?.[p.team]===p.id,viceCaptain:!p.role&&r.viceCaptains?.[p.team]===p.id})),teamNames:r.teamNames||{A:'Team A',B:'Team B'},refereeId:r.refereeId||null,commentatorId:r.commentatorId||null,officialIds:[...r.officialIds||[]],roomAdminId:r.roomAdminId||null,teams:{A:r.players.filter(p=>p.team==='A'&&!p.role).length,B:r.players.filter(p=>p.team==='B'&&!p.role).length}}}
function sendRoom(r){r.players.forEach(p=>send(p.ws,{...roomInfo(r),playerId:p.id,team:p.team}))}
function publicRooms(){return [...rooms.values()].filter(r=>!r.started).map(r=>({code:r.code,access:r.access||'free',players:r.players.length,A:r.players.filter(p=>p.team==='A').length,B:r.players.filter(p=>p.team==='B').length,status:r.phase,hostName:r.players[0]?.name||'Host'})).sort((a,b)=>b.players-a.players||a.code.localeCompare(b.code))}
function broadcastRoomList(){const msg={type:'rooms',rooms:publicRooms()};wss.clients.forEach(ws=>send(ws,msg))}
function resetMatch(r){r.started=true;r.phase='toss';r.innings=1;r.score=0;r.wickets=0;r.balls=0;r.target=0;r.gameOver=false;r.choices=new Map();r.lockedUntil=0;r.firstInnings=null;r.toss=null;r.tossWinner=null;r.decision=null;r.batterPos=0;r.bowlerPos=0;r.battingTeam=null;r.bowlingTeam=null;r.ballHistory=[];r.inningsHistory=[];r.playerStats={};r.mom=null;r.commentary=`🪙 Toss time — ${r.players[0].name} calls the coin.`;broadcast(r,{type:'started'});broadcastState(r)}
function start(r){const active=r.players.filter(p=>!p.role);if(r.started||active.length<2||!r.players.some(p=>p.team==='A'&&!p.role)||!r.players.some(p=>p.team==='B'&&!p.role)||active.some(p=>p.team!=='A'&&p.team!=='B'))return;resetMatch(r)}
function finishInnings(r){
  r.inningsHistory.push({innings:r.innings,team:r.battingTeam,score:r.score,wickets:r.wickets,balls:r.balls});
  const hist=r.inningsHistory;
  if((r.matchType||'limited')!=='test'){
    if(r.innings===1){r.firstInnings={team:r.battingTeam,score:r.score};r.innings=2;r.phase='playing';r.score=0;r.wickets=0;r.balls=0;r.target=r.firstInnings.score+1;[r.battingTeam,r.bowlingTeam]=[r.bowlingTeam,r.battingTeam];r.batterPos=0;r.bowlerPos=0;r.choices=new Map();r.commentary=`🏏 Innings break. ${r.battingTeam} need ${r.target} runs to win.`;r.lockedUntil=Date.now()+2000;broadcastState(r);return;}
    const chaseWon=r.score>=r.target;const winner=chaseWon?r.battingTeam:r.bowlingTeam;r.gameOver=true;r.phase='finished';r.mom=Object.entries(r.playerStats||{}).map(([id,x])=>({id,...x})).sort((a,b)=>(b.runs+b.wickets*20)-(a.runs+a.wickets*20))[0]||null;r.commentary=chaseWon?`🏆 ${winner} wins by ${maxWickets(r)-r.wickets} wickets!`:`🏆 ${winner} wins by ${r.target-1-r.score} runs!`;r.lockedUntil=0;broadcastState(r);broadcast(r,{type:'finished',message:r.commentary,state:publicState(r,r.players[0].id)});return;
  }
  if(r.innings<4){
    const first=hist[0],second=hist[1];
    if(r.innings===1){r.innings=2;r.battingTeam=secondTeamFor(first.team,r.players);r.bowlingTeam=first.team;r.target=0;}
    else if(r.innings===2){
      const lead=(first.score||0)-(second.score||0);
      if(lead>=200){r.followOn=true;r.innings=3;r.battingTeam=second.team;r.bowlingTeam=first.team;r.target=0;r.commentary=`📜 Follow-on enforced: ${second.team} bat again.`;}
      else{r.innings=3;r.battingTeam=first.team;r.bowlingTeam=second.team;r.target=0;r.commentary=`📜 3rd innings begins: ${first.team} bat again.`;}
    } else {
      r.innings=4;r.battingTeam=second.team;r.bowlingTeam=first.team;
      const firstScore=hist[0].score||0, secondScore=hist[1].score||0, thirdScore=hist[2].score||0;
      r.target=Math.max(0,(firstScore+thirdScore-secondScore)+1);
      r.commentary=`📜 4th innings begins. ${r.battingTeam} need ${r.target} runs to win.`;
    }
    r.score=0;r.wickets=0;r.balls=0;r.batterPos=0;r.bowlerPos=0;r.choices=new Map();r.lockedUntil=Date.now()+2000;broadcastState(r);return;
  }
  const byTeam={};hist.forEach(x=>byTeam[x.team]=(byTeam[x.team]||0)+x.score);
  const teams=Object.keys(byTeam);const a=teams[0],b=teams[1];let winner=null,draw=false;
  if(r.score>=r.target && r.target>0) winner=r.battingTeam;
  else {const finalA=byTeam[a]||0,finalB=byTeam[b]||0;if(finalA===finalB)draw=true;else winner=finalA>finalB?a:b;}
  r.gameOver=true;r.phase='finished';r.mom=Object.entries(r.playerStats||{}).map(([id,x])=>({id,...x})).sort((x,y)=>(y.runs+y.wickets*20)-(x.runs+x.wickets*20))[0]||null;r.commentary=draw?'🤝 Test Match drawn.':`🏆 Test Match: ${winner} wins.`;r.lockedUntil=0;broadcastState(r);broadcast(r,{type:'finished',message:r.commentary,state:publicState(r,r.players[0].id)});
}
function secondTeamFor(firstTeam,players){return firstTeam==='A'?'B':'A';}
function resolve(r){
 const bat=teamPlayers(r,r.battingTeam),bowl=teamPlayers(r,r.bowlingTeam),activeBat=bat[r.batterPos%bat.length],activeBowl=bowl[r.bowlerPos%bowl.length];
 if(!activeBat||!activeBowl)return;
 const a=r.choices.get(activeBat.id),b=r.choices.get(activeBowl.id);if(a===undefined||b===undefined||r.gameOver)return;
 r.choices=new Map();r.balls++;const out=a===b;let runs=0,event='run';
 if(out){r.wickets++;event='out';r.commentary=`☝️ WICKET! ${activeBat.name} and ${activeBowl.name} both chose ${a}.`;r.batterPos++}else{runs=a;r.score+=runs;event=runs===4?'four':runs===6?'six':'run';r.commentary=runs===0?'Dot ball.':`${runs} run${runs===1?'':'s'} added.`}
 const bs=r.playerStats[activeBat.id]||(r.playerStats[activeBat.id]={name:activeBat.name,team:activeBat.team,runs:0,wickets:0,balls:0}); const bw=r.playerStats[activeBowl.id]||(r.playerStats[activeBowl.id]={name:activeBowl.name,team:activeBowl.team,runs:0,wickets:0,balls:0}); bs.balls++; if(!out)bs.runs+=runs; if(out)bw.wickets++; r.ballHistory.push({innings:r.innings,ball:r.balls,batter:activeBat.name,batterId:activeBat.id,bowler:activeBowl.name,bowlerId:activeBowl.id,batterChoice:a,bowlerChoice:b,runs,out,score:r.score,wickets:r.wickets,at:Date.now()});
 r.bowlerPos++;
 const ballLimit=(r.matchType||'limited')==='test'?1200:Math.max(6,(Number(r.overs)||5)*6); const inningsEnd=r.wickets>=maxWickets(r)||r.balls>=ballLimit||((r.matchType||'limited')!=='test'&&r.innings===2&&r.score>=r.target)||(r.matchType==='test'&&r.innings===4&&r.score>=r.target);
 r.lockedUntil=Date.now()+1500;broadcast(r,{type:'ball',event,state:publicState(r,r.players[0].id)});
 if(inningsEnd)return setTimeout(()=>finishInnings(r),1500);
 broadcastState(r)
}
const json=(res,status,obj)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(obj))};
const server=http.createServer((req,res)=>{let u=(req.url||'/').split('?')[0];
 const cookies=String(req.headers.cookie||'');let vm=(cookies.match(/(?:^|; )hca_vid=([^;]+)/)||[])[1];if(!vm){vm=crypto.randomBytes(12).toString('hex');res.setHeader('Set-Cookie',`hca_vid=${vm}; Max-Age=31536000; Path=/; SameSite=Lax`)}if(!visitorIds.has(vm)){visitorIds.add(vm);analytics.uniqueVisitors=(analytics.uniqueVisitors||0)+1}analytics.visits=(analytics.visits||0)+1;const day=new Date().toISOString().slice(0,10);analytics.daily[day]=(analytics.daily[day]||0)+1;if((analytics.visits%25)===0)saveAnalytics();
 if(req.method==='POST'&&u==='/api/owner-recover'){let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const m=JSON.parse(body||'{}'),identifier=String(m.identifier||'').trim().toLowerCase(),gameId=String(m.gameId||'').trim(),recoveryPin=String(m.recoveryPin||''),newPassword=String(m.newPassword||''),name=safeText(m.name||'Owner',20);const ownerG=(fileOwnerGameId()||ownerGameId()).trim();if(!validId(identifier)||!validGameId(gameId)||!ownerG||gameId.toLowerCase()!==ownerG.toLowerCase())return json(res,400,{ok:false,error:'Owner recovery is only available for the configured owner Game ID.'});if(newPassword.length<6)return json(res,400,{ok:false,error:'New password must be at least 6 characters.'});if(!recoveryPin||!ownerRecoveryPin()||hash(recoveryPin)!==hash(ownerRecoveryPin()))return json(res,401,{ok:false,error:'Invalid owner recovery PIN.'});let acc=accounts[identifier];const existingOwner=Object.values(accounts).find(a=>String(a.gameId||'').toLowerCase()===gameId.toLowerCase()&&String(a.identifier||'').toLowerCase()!==identifier);if(existingOwner&&!acc)return json(res,409,{ok:false,error:'This Owner Game ID is already linked to another account identifier.'});if(acc&&String(acc.gameId||'').toLowerCase()!==gameId.toLowerCase())return json(res,409,{ok:false,error:'This email/phone is already linked to a different Game ID.'});if(!acc){acc={playerId:'HCA-'+crypto.randomBytes(5).toString('hex').toUpperCase(),gameId,identifier,name,passwordHash:hash(newPassword),role:'OWNER',subscription:{plan:'OWNER_PREMIUM',status:'ACTIVE',source:'OWNER',premium:true,startedAt:Date.now(),expiresAt:null,paymentId:null,verificationStatus:'NOT_REQUIRED'},createdAt:Date.now(),stats:{matches:0,wins:0,losses:0,runs:0,wickets:0,highest:0,fifties:0,hundreds:0,fours:0,sixes:0}};accounts[identifier]=acc;}else{acc.gameId=gameId;acc.role='OWNER';acc.passwordHash=hash(newPassword);acc.name=name;acc.subscription={...(acc.subscription||{}),plan:'OWNER_PREMIUM',status:'ACTIVE',source:'OWNER',premium:true,expiresAt:null};}saveAccounts();for(const [t,pid] of sessions.entries())if(pid===acc.playerId)sessions.delete(t);resetRequests=resetRequests.filter(x=>x.playerId!==acc.playerId);saveResets();return json(res,200,{ok:true,message:'Owner account recovered successfully. You can now login with the new password.',gameId:acc.gameId,identifier:acc.identifier});}catch(e){return json(res,400,{ok:false,error:'Invalid owner recovery request.'})}});return;}
if(req.method==='POST'&&u==='/api/password-reset/request'){let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const m=JSON.parse(body||'{}'),identifier=String(m.identifier||'').trim().toLowerCase(),gameId=String(m.gameId||'').trim();if(!validId(identifier)||!validGameId(gameId))return json(res,400,{ok:false,error:'Enter the registered email/phone and Game ID.'});const acc=accounts[identifier];if(!acc||String(acc.gameId||'').toLowerCase()!==gameId.toLowerCase())return json(res,200,{ok:true,message:'If the account details match, a reset request has been sent to the Admin Team.',requestId:null});const existing=resetRequests.find(x=>x.playerId===acc.playerId&&['PENDING','APPROVED'].includes(x.status));if(existing)return json(res,200,{ok:true,message:'A password reset request is already pending. Contact the Admin Team with your Game ID.',requestId:existing.id});const r={id:'PWD-'+crypto.randomBytes(4).toString('hex').toUpperCase(),playerId:acc.playerId,gameId:acc.gameId,identifier:acc.identifier,name:acc.name,status:'PENDING',createdAt:Date.now(),updatedAt:Date.now(),codeHash:'',expiresAt:null};resetRequests.unshift(r);resetRequests=resetRequests.slice(0,200);saveResets();return json(res,200,{ok:true,message:'Password reset request sent to the Admin Team. Contact the Admin Team/WhatsApp 9354041918 with your request ID.',requestId:r.id,whatsapp:'919354041918'});}catch(e){return json(res,400,{ok:false,error:'Invalid request.'})}});return;}
if(req.method==='POST'&&u==='/api/password-reset/complete'){let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const m=JSON.parse(body||'{}'),identifier=String(m.identifier||'').trim().toLowerCase(),gameId=String(m.gameId||'').trim(),resetCode=String(m.resetCode||'').trim(),newPassword=String(m.newPassword||'');if(!validId(identifier)||!validGameId(gameId)||!/^\d{6}$/.test(resetCode)||newPassword.length<6)return json(res,400,{ok:false,error:'Enter valid account details, 6-digit reset code and a password of at least 6 characters.'});const acc=accounts[identifier];const r=resetRequests.find(x=>x.playerId===acc?.playerId&&x.gameId?.toLowerCase()===gameId.toLowerCase()&&x.status==='APPROVED');if(!acc||!r||!r.expiresAt||Number(r.expiresAt)<Date.now()||hash(resetCode)!==r.codeHash)return json(res,400,{ok:false,error:'Invalid or expired reset code.'});acc.passwordHash=hash(newPassword);saveAccounts();r.status='USED';r.updatedAt=Date.now();r.codeHash='';r.expiresAt=null;saveResets();for(const [t,pid] of sessions.entries())if(pid===acc.playerId)sessions.delete(t);return json(res,200,{ok:true,message:'Password reset successfully. You can now login with the new password.'});}catch(e){return json(res,400,{ok:false,error:'Invalid request.'})}});return;}
if(req.method==='POST'&&(u==='/api/register'||u==='/api/login')){let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const m=JSON.parse(body||'{}'),identifier=String(m.identifier||'').trim().toLowerCase(),password=String(m.password||'');if(password.length<6)return json(res,400,{error:'Enter a valid login identifier and password of at least 6 characters.'});if(u==='/api/register'){if(!validId(identifier))return json(res,400,{error:'Use a valid email/phone and password of at least 6 characters.'});if(accounts[identifier])return json(res,409,{error:'Player account already exists.'});const requestedGameId=safeText(m.gameId||'',20);if(!validGameId(requestedGameId))return json(res,400,{error:'Game ID must be 3-20 letters, numbers or underscore.'});if(gameIdTaken(requestedGameId))return json(res,409,{error:'That Game ID is already taken.'});const playerId='HCA-'+crypto.randomBytes(5).toString('hex').toUpperCase();accounts[identifier]={playerId,gameId:requestedGameId,identifier,name:safeText(m.name||'Player',20),passwordHash:hash(password),role:'USER',subscription:{plan:'FREE',status:'FREE',source:'NONE',premium:false,startedAt:null,expiresAt:null,paymentId:null,verificationStatus:'NOT_REQUIRED'},createdAt:Date.now(),stats:{matches:0,wins:0,losses:0,runs:0,wickets:0,highest:0,fifties:0,hundreds:0,fours:0,sixes:0}};const acc=accounts[identifier];if((ownerGameId()&&requestedGameId.toLowerCase()===ownerGameId().toLowerCase())||(ownerEmail()&&identifier===ownerEmail()))acc.role='OWNER';saveAccounts();const tk=token();sessions.set(tk,playerId);const sub=subscriptionState(acc);return json(res,200,{ok:true,token:tk,playerId,gameId:requestedGameId,name:acc.name,role:acc.role,isAdmin:adminAllowedAccount(acc),subscription:sub});}const acc=accountForLogin(identifier);if(!acc||acc.passwordHash!==hash(password))return json(res,401,{error:'Invalid login details. Check your email/phone or Game ID and password.'});if(!acc.role)acc.role='USER';const sub=subscriptionState(acc);const tk=token();sessions.set(tk,acc.playerId);return json(res,200,{ok:true,token:tk,playerId:acc.playerId,gameId:acc.gameId,name:acc.name,role:acc.role,isAdmin:adminAllowedAccount(acc),subscription:sub});}catch(e){json(res,400,{error:'Invalid request.'})}});return;}
if(u==='/api/check-game-id'){const gid=String(new URL(req.url,'http://localhost').searchParams.get('gameId')||'').trim();if(!validGameId(gid))return json(res,400,{ok:false,available:false,error:'Game ID must be 3-20 letters, numbers or underscore.'});return json(res,200,{ok:true,available:!gameIdTaken(gid),gameId:gid});}
 if(u==='/api/me'){const a=auth(req.headers['x-session-token']);if(!a)return json(res,401,{ok:false,error:'Unauthorized'});const sub=subscriptionState(a);return json(res,200,{ok:true,playerId:a.playerId,gameId:a.gameId,name:a.name,role:a.role||'USER',subscription:sub,stats:a.stats||{}});}
 if(u==='/api/announcement'){return json(res,200,{ok:true,enabled:!!announcement.enabled,text:announcement.enabled?announcement.text:'',updatedAt:announcement.updatedAt||null});}
if(u==='/api/admin/status'){const acc=auth(req.headers['x-session-token']);return json(res,200,{ok:true,signedIn:!!acc,allowed:adminAllowedAccount(acc),owner:isOwnerAccount(acc),passwordConfigured:!!adminPasswordHash()});}
if(req.method==='POST'&&u==='/api/admin/session-login'){const acc=auth(req.headers['x-session-token']);if(!adminAllowedAccount(acc))return json(res,401,{ok:false,error:'Admin Team access denied.'});let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const m=JSON.parse(body||'{}'),password=String(m.password||'');if(password.length<1)return json(res,400,{ok:false,error:'Admin password is required.'});if(!adminPasswordMatches(password))return json(res,401,{ok:false,error:'Wrong Admin password.'});const t=adminToken();adminSessions.set(t,{gameId:acc.gameId,playerId:acc.playerId,at:Date.now(),owner:isOwnerAccount(acc)});return json(res,200,{ok:true,token:t,gameId:acc.gameId,name:acc.name,role:acc.role||'ADMIN',owner:isOwnerAccount(acc)});}catch(e){return json(res,400,{ok:false,error:'Invalid request.'})}});return;}
if(req.method==='POST'&&u==='/api/admin/login'){let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const m=JSON.parse(body||'{}'),gid=safeText(m.gameId||'',20).trim(),pin=String(m.pin||'');if(!gid||!pin)return json(res,400,{ok:false,error:'Game ID and Team PIN are required.'});if(!adminAllowedGameId(gid)||!adminPasswordMatches(pin))return json(res,401,{ok:false,error:'Admin Team access denied.'});const t=adminToken();adminSessions.set(t,{gameId:gid,at:Date.now(),owner:gid.toLowerCase()===fileOwnerGameId().toLowerCase()});return json(res,200,{ok:true,token:t,gameId:gid})}catch(e){return json(res,400,{ok:false,error:'Invalid request.'})}});return;}
if(req.method==='POST'&&u==='/api/admin/change-password'){if(!requireAdmin(req))return json(res,401,{ok:false,error:'Unauthorized'});const s=adminSessions.get(String(req.headers['x-admin-session']||''));if(!s?.owner)return json(res,403,{ok:false,error:'Only the owner can change the Admin password.'});let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const m=JSON.parse(body||'{}'),next=String(m.newPassword||'');if(next.length<8)return json(res,400,{ok:false,error:'Use an Admin password of at least 8 characters.'});adminTeamFile.pinHash=hash(next);adminTeamFile.pin='';saveAdminTeam();return json(res,200,{ok:true,message:'Admin password changed.'})}catch(e){return json(res,400,{ok:false,error:'Invalid request.'})}});return;}
if(req.method==='POST'&&u==='/api/admin/setup-password'){const acc=auth(req.headers['x-session-token']);if(!isOwnerAccount(acc))return json(res,403,{ok:false,error:'Only the owner can set the Admin password.'});if(adminTeamFile.pinHash)return json(res,409,{ok:false,error:'Admin password is already configured. Use Change Password from Admin.'});let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const m=JSON.parse(body||'{}'),next=String(m.newPassword||'');if(next.length<8)return json(res,400,{ok:false,error:'Use an Admin password of at least 8 characters.'});adminTeamFile.pinHash=hash(next);adminTeamFile.pin='';saveAdminTeam();return json(res,200,{ok:true,message:'Admin password configured.'})}catch(e){return json(res,400,{ok:false,error:'Invalid request.'})}});return;}
if(req.method==='POST'&&u==='/api/admin/announcement'){if(!requireAdmin(req))return json(res,401,{ok:false,error:'Unauthorized'});let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const m=JSON.parse(body||'{}');const text=safeText(m.text||'',1000).trim();if(!text)return json(res,400,{ok:false,error:'Announcement text is required.'});announcement={enabled:true,text,updatedAt:Date.now()};saveAnnouncement();if(typeof wss!=='undefined')wss.clients.forEach(ws=>send(ws,{type:'announcement',announcement}));return json(res,200,{ok:true,announcement})}catch(e){return json(res,400,{ok:false,error:'Invalid request.'})}});return;}
if(req.method==='POST'&&u==='/api/admin/logout'){const t=String(req.headers['x-admin-session']||'');adminSessions.delete(t);return json(res,200,{ok:true});}
if(req.method==='DELETE'&&u==='/api/admin/announcement'){if(!requireAdmin(req))return json(res,401,{ok:false,error:'Unauthorized'});announcement={enabled:false,text:'',updatedAt:Date.now()};saveAnnouncement();if(typeof wss!=='undefined')wss.clients.forEach(ws=>send(ws,{type:'announcement',announcement}));return json(res,200,{ok:true,announcement});}
if(u==='/api/admin/players'){if(!requireAdmin(req))return json(res,401,{ok:false,error:'Unauthorized'});const list=Object.values(accounts).map(a=>{const sub=subscriptionState(a);return {playerId:a.playerId,gameId:a.gameId,name:a.name,identifier:a.identifier,role:a.role||'USER',subscription:sub,createdAt:a.createdAt,stats:a.stats||{}}});return json(res,200,{ok:true,players:list});}
 if(req.method==='POST' && u==='/api/admin/role'){if(!requireAdmin(req))return json(res,401,{ok:false,error:'Unauthorized'});let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const m=JSON.parse(body||'{}'),a=accountForPlayerId(String(m.playerId||''));if(!a)return json(res,404,{ok:false,error:'Player not found'});const role=String(m.role||'USER').toUpperCase();if(!['USER','OWNER','ADMIN'].includes(role))return json(res,400,{ok:false,error:'Invalid role'});a.role=role;if(role==='OWNER'){a.subscription={plan:'OWNER_PREMIUM',status:'ACTIVE',source:'OWNER',premium:true,startedAt:Date.now(),expiresAt:null,paymentId:null,verificationStatus:'OWNER_ENTITLEMENT'};}saveAccounts();return json(res,200,{ok:true,player:{playerId:a.playerId,gameId:a.gameId,role:a.role,subscription:subscriptionState(a)}});}catch(e){return json(res,400,{ok:false,error:'Invalid request.'})}});return;}
 if(req.method==='POST' && u==='/api/admin/subscription'){if(!requireAdmin(req))return json(res,401,{ok:false,error:'Unauthorized'});let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const m=JSON.parse(body||'{}'),pid=String(m.playerId||'');const a=accountForPlayerId(pid);if(!a)return json(res,404,{ok:false,error:'Player not found'});const action=String(m.action||'').toLowerCase();if(action==='grant'){const days=Math.max(1,Math.min(3650,Number(m.days)||30));const now=Date.now();a.subscription={plan:'ADMIN_GRANT',status:'ACTIVE',source:'ADMIN_GRANT',premium:true,startedAt:now,expiresAt:now+days*86400000,paymentId:null,verificationStatus:'ADMIN_APPROVED',reason:safeText(m.reason||'Admin grant',120)};}else if(action==='revoke'){a.subscription={plan:'FREE',status:'FREE',source:'ADMIN_REVOKE',premium:false,startedAt:null,expiresAt:null,paymentId:null,verificationStatus:'REVOKED'};}else if(action==='verify'){const tokenValue=safeText(m.purchaseToken||'',500);if(!tokenValue)return json(res,400,{ok:false,error:'Purchase token required for Google Play verification.'});a.subscription={plan:'GOOGLE_PLAY',status:'PENDING',source:'GOOGLE_PLAY',premium:false,startedAt:Date.now(),expiresAt:null,paymentId:safeText(m.paymentId||'',200),purchaseToken:tokenValue,verificationStatus:'PENDING_BACKEND_GOOGLE_CHECK'};}else return json(res,400,{ok:false,error:'Unknown action'});saveAccounts();return json(res,200,{ok:true,player:{playerId:a.playerId,gameId:a.gameId,subscription:subscriptionState(a)}});}catch(e){return json(res,400,{ok:false,error:'Invalid request.'})}});return;}
 if(u==='/api/subscription-info'){const a=auth(req.headers['x-session-token']);if(!a)return json(res,401,{ok:false,error:'Unauthorized'});return json(res,200,{ok:true,subscription:subscriptionState(a)});}
 if(req.method==='POST'&&u==='/api/support/ticket'){const acc=auth(req.headers['x-session-token']);if(!acc)return json(res,401,{ok:false,error:'Please login first.'});let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const m=JSON.parse(body||'{}'),category=safeText(m.category||'General',40)||'General',message=safeText(m.message||'',1200).trim();if(!message)return json(res,400,{ok:false,error:'Please describe your problem.'});const t={id:'SUP-'+crypto.randomBytes(4).toString('hex').toUpperCase(),playerId:acc.playerId,gameId:acc.gameId,name:acc.name,category,message,status:'OPEN',createdAt:Date.now(),updatedAt:Date.now(),adminResponse:''};supportTickets.unshift(t);supportTickets=supportTickets.slice(0,500);saveSupport();return json(res,200,{ok:true,ticket:t,whatsapp:'919354041918'});}catch(e){return json(res,400,{ok:false,error:'Invalid request.'})}});return;}
 if(u==='/api/support/my'){const acc=auth(req.headers['x-session-token']);if(!acc)return json(res,401,{ok:false,error:'Unauthorized'});return json(res,200,{ok:true,tickets:supportTickets.filter(t=>t.playerId===acc.playerId).slice(0,30)});}
 if(u==='/api/admin/password-reset'){if(!requireAdmin(req))return json(res,401,{ok:false,error:'Unauthorized'});return json(res,200,{ok:true,requests:resetRequests.slice(0,100).map(x=>({...x,codeHash:undefined}))});}
 if(req.method==='POST'&&u==='/api/admin/password-reset'){if(!requireAdmin(req))return json(res,401,{ok:false,error:'Unauthorized'});let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const m=JSON.parse(body||'{}'),requestId=String(m.requestId||''),action=String(m.action||'').toLowerCase(),r=resetRequests.find(x=>x.id===requestId);if(!r)return json(res,404,{ok:false,error:'Reset request not found.'});if(action==='reject'){r.status='REJECTED';r.updatedAt=Date.now();r.codeHash='';r.expiresAt=null;saveResets();return json(res,200,{ok:true,request:r});}if(action==='approve'){if(r.status==='USED')return json(res,400,{ok:false,error:'Request already used.'});const resetCode=String(Math.floor(100000+Math.random()*900000));r.status='APPROVED';r.codeHash=hash(resetCode);r.expiresAt=Date.now()+15*60*1000;r.updatedAt=Date.now();saveResets();return json(res,200,{ok:true,request:{...r,codeHash:undefined},resetCode,expiresAt:r.expiresAt});}return json(res,400,{ok:false,error:'Unknown action.'});}catch(e){return json(res,400,{ok:false,error:'Invalid request.'})}});return;}
 if(u==='/api/admin/support'){if(!requireAdmin(req))return json(res,401,{ok:false,error:'Unauthorized'});return json(res,200,{ok:true,tickets:supportTickets.slice(0,200)});}
 if(req.method==='POST'&&u==='/api/admin/support'){if(!requireAdmin(req))return json(res,401,{ok:false,error:'Unauthorized'});let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const m=JSON.parse(body||'{}'),t=supportTickets.find(x=>x.id===String(m.ticketId||''));if(!t)return json(res,404,{ok:false,error:'Ticket not found.'});const status=['OPEN','IN_PROGRESS','RESOLVED'].includes(String(m.status||''))?String(m.status):t.status;const response=safeText(m.adminResponse||'',1200).trim();t.status=status;t.adminResponse=response;t.updatedAt=Date.now();saveSupport();return json(res,200,{ok:true,ticket:t});}catch(e){return json(res,400,{ok:false,error:'Invalid request.'})}});return;}
 if(u==='/api/analytics'){return json(res,200,{ok:true,registeredPlayers:Object.keys(accounts).length,visits:analytics.visits||0,uniqueVisitors:analytics.uniqueVisitors||0,openRooms:publicRooms().length,onlineSockets:wss.clients.size,todayVisits:analytics.daily[new Date().toISOString().slice(0,10)]||0})};
 if(u==='/admin_team.json'||u==='/players.json'||u==='/announcement.json'||u==='/analytics.json'||u==='/support_tickets.json'||u==='/password_reset_requests.json'){res.writeHead(403,{'Content-Type':'text/plain'});return res.end('Forbidden');}
if(u==='/admin'){
   const f=path.join(ROOT,'admin.html');res.writeHead(200,{'Content-Type':'text/html','Cache-Control':'no-store'});return fs.createReadStream(f).pipe(res);
 }
 if(u==='/api/admin/team'){if(!requireAdmin(req))return json(res,401,{ok:false,error:'Unauthorized'});const s=adminSessions.get(String(req.headers['x-admin-session']||''));if(!s?.owner)return json(res,403,{ok:false,error:'Only the owner can manage Admin users.'});return json(res,200,{ok:true,ownerGameId:fileOwnerGameId()||ownerGameId(),teamIds:fileAdminTeamIds()});}
 if(req.method==='POST'&&u==='/api/admin/team'){if(!requireAdmin(req))return json(res,401,{ok:false,error:'Unauthorized'});const s=adminSessions.get(String(req.headers['x-admin-session']||''));if(!s?.owner)return json(res,403,{ok:false,error:'Only the owner can manage Admin users.'});let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const m=JSON.parse(body||'{}'),gid=String(m.gameId||'').trim().toLowerCase(),action=String(m.action||'add').toLowerCase();if(!validGameId(gid))return json(res,400,{ok:false,error:'Enter a valid Game ID.'});if(gid===fileOwnerGameId().toLowerCase()||gid===ownerGameId().toLowerCase())return json(res,400,{ok:false,error:'Owner is already an Admin.'});let ids=fileAdminTeamIds();if(action==='remove')ids=ids.filter(x=>x!==gid);else if(!ids.includes(gid))ids.push(gid);adminTeamFile.teamIds=ids;saveAdminTeam();return json(res,200,{ok:true,teamIds:ids});}catch(e){return json(res,400,{ok:false,error:'Invalid request.'})}});return;}
 if(u==='/api/admin/overview'){
   if(!requireAdmin(req))return json(res,401,{ok:false,error:'Unauthorized'});
   const today=new Date().toISOString().slice(0,10), all=Object.values(accounts), subs=all.map(subscriptionState);
   return json(res,200,{ok:true,registeredPlayers:all.length,freePlayers:subs.filter(x=>!x.premium&&x.status!=='EXPIRED').length,activeSubscribers:subs.filter(x=>x.premium&&x.source!=='OWNER').length,expiredSubscribers:subs.filter(x=>x.status==='EXPIRED').length,ownerAccounts:subs.filter(x=>x.source==='OWNER').length,visits:analytics.visits||0,uniqueVisitors:analytics.uniqueVisitors||0,todayVisits:analytics.daily?.[today]||0,openRooms:publicRooms().length,onlineConnections:wss.clients.size,rooms:rooms.size,serverTime:new Date().toISOString(),subscriptionPromo:{basePriceINR:100,tier1:{from:1,to:50,priceINR:0,label:'First 50 — Free'},tier2:{from:51,to:100,priceINR:50,label:'Next 50 — 50% off'},tier3:{from:101,to:200,priceINR:70,label:'Next 100 — 30% off'},tier4:{from:201,priceINR:100,label:'After 200 — Full price'}}});
 }
 if(u==='/health'){return json(res,200,{ok:true,rooms:rooms.size,players:Object.keys(accounts).length,visits:analytics.visits||0,uniqueVisitors:analytics.uniqueVisitors||0,onlineSockets:wss.clients.size,persistence:pgPool?'postgres':'file'})};
 if(u==='/api/health'){res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});return res.end(JSON.stringify({ok:true,rooms:rooms.size,players:Object.keys(accounts).length,visits:analytics.visits||0,uniqueVisitors:analytics.uniqueVisitors||0,onlineSockets:wss.clients.size}));}
if(u==='/')u='/Hand_Cricket_Arena.html';const f=path.join(ROOT,path.normalize(u));if(!f.startsWith(ROOT)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);return res.end('Not found')}const ext=path.extname(f),types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.mp3':'audio/mpeg','.txt':'text/plain','.gif':'image/gif'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(f).pipe(res)});
const wss=new WebSocket.Server({server});
wss.on('connection',ws=>{ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return send(ws,{type:'error',message:'Invalid message'})}const name=String(m.name||'Player').slice(0,20);
 if(m.type==='listRooms'){return send(ws,{type:'rooms',rooms:publicRooms()})}
 if(m.type==='create'){const acc=auth(m.token);if(!acc)return send(ws,{type:'error',message:'Please login/register first.'});const access=(String(m.access||'free').toLowerCase()==='premium'?'premium':'free');if(access==='premium'&&!isPremiumAccount(acc))return send(ws,{type:'error',message:'Active Premium subscription required to create a Premium room.'});const r={code:code(),password:'',access,matchType:String(m.matchType||'limited'),overs:Math.max(1,Math.min(50,Number(m.overs)||5)),banList:new Set(),captains:{A:null,B:null},viceCaptains:{A:null,B:null},teamNames:{A:'Team A',B:'Team B'},refereeId:null,commentatorId:null,officialIds:new Set(),players:[],roomAdminId:null,started:false,phase:'lobby',innings:1,score:0,wickets:0,balls:0,target:0,battingTeam:null,bowlingTeam:null,batterPos:0,bowlerPos:0,choices:new Map(),lockedUntil:0,gameOver:false,commentary:'Waiting for players...',firstInnings:null,toss:null,tossWinner:null,decision:null,ballHistory:[],inningsHistory:[],playerStats:{},mom:null};const p={id:id(),playerId:acc.playerId,name:acc.name||name,ws,ready:false,online:true,team:null,role:null};r.players.push(p);r.roomAdminId=p.id;r.captains.A=null;r.captains.B=null;r.viceCaptains.A=null;r.viceCaptains.B=null;rooms.set(r.code,r);sendRoom(r);broadcastRoomList();return}
 let r=rooms.get(String(m.room||'').toUpperCase());
 if(m.type==='join'){const acc=auth(m.token);if(!acc)return send(ws,{type:'error',message:'Please login/register first.'});if(!r)return send(ws,{type:'error',message:'Room not found.'});if(r.access==='premium'&&!isPremiumAccount(acc))return send(ws,{type:'error',message:'This is a Premium room. Active subscription required.'});const existing=r.players.find(p=>p.playerId===acc.playerId&&p.online===false);if(existing){existing.ws=ws;existing.online=true;sendRoom(r);broadcastState(r);broadcastRoomList();return}if(r.started)return send(ws,{type:'error',message:'Match already started.'});if(r.banList.has(acc.gameId.toLowerCase()))return send(ws,{type:'error',message:'You are banned from this room.'});const p={id:id(),playerId:acc.playerId,name:acc.name||name,ws,ready:false,online:true,team:null,role:null};r.players.push(p);assignCaptains(r);sendRoom(r);broadcastRoomList();return}
 if(!r)return send(ws,{type:'error',message:'Join or create a room first.'});const me=r.players.find(p=>p.ws===ws);if(!me)return send(ws,{type:'error',message:'Player not in room.'});
 if(m.type==='team'){if(r.started||me.role)return;const t=String(m.team||'').toUpperCase();if(t!=='A'&&t!=='B')return;if(teamPlayers(r,t).length>=15)return send(ws,{type:'error',message:'Each playing team can have maximum 15 players.'});me.team=t;me.ready=false;assignCaptains(r);sendRoom(r);broadcastRoomList();return}
 if(m.type==='teamAdmin'){if(r.started||authorityLevel(r,me)<4)return;const pid=String(m.playerId||''),t=String(m.team||'').toUpperCase();if(!['A','B'].includes(t))return;const target=r.players.find(p=>p.id===pid&&!p.role);if(!target||teamPlayers(r,t).length>=15)return;target.team=t;target.ready=false;assignCaptains(r);sendRoom(r);return}
 if(m.type==='chat'){const text=safeText(m.text,240);if(!text)return;const scope=m.scope==='team'?'team':'public';if(scope==='public'&&!canManage(r,me))return send(ws,{type:'error',message:'Public chat is limited to room admin, captains, referee, officials and commentator.'});const msg={type:'chat',name:me.name,team:me.team,text,scope,at:Date.now()};if(scope==='team')sendTeam(r,me.team,msg);else broadcast(r,msg);return}
 if(m.type==='voice'){const data=String(m.data||'');if(!data||data.length>2500000)return send(ws,{type:'error',message:'Voice message too large.'});const scope=m.scope==='team'?'team':'public';if(scope==='public'&&!canManage(r,me))return send(ws,{type:'error',message:'Only captain, room admin, referee or official can send public voice.'});sendVoice(r,me,scope,data);return}
 if(m.type==='emoji'){const emoji=safeText(m.emoji,12),phrase=safeText(m.phrase,40);if(!emoji)return;const scope=m.scope==='team'?'team':'public';if(scope==='public'&&!canManage(r,me))return send(ws,{type:'error',message:'Only captain, room admin, referee or official can send public emoji.'});const msg={type:'emoji',name:me.name,team:me.team,emoji,phrase,scope,at:Date.now()};if(scope==='team')sendTeam(r,me.team,msg);else broadcast(r,msg);return}
 if(m.type==='captain'){if(r.started)return;const lvl=authorityLevel(r,me);if(lvl<3 || (r.roomAdminId!==me.id && !isReferee(r,me) && !r.officialIds?.has(me.id)))return;const pid=String(m.playerId||'');const target=r.players.find(p=>p.id===pid&&!p.role);if(!target||!target.team)return;assignCaptains(r);r.captains[target.team]=target.id;if(r.viceCaptains?.[target.team]===target.id)r.viceCaptains[target.team]=null;sendRoom(r);return}
 if(m.type==='viceCaptain'){if(r.started)return;const lvl=authorityLevel(r,me);if(lvl<3)return;const pid=String(m.playerId||'');const target=r.players.find(p=>p.id===pid&&!p.role&&p.team);if(!target)return;if(!r.viceCaptains)r.viceCaptains={A:null,B:null};r.viceCaptains[target.team]=target.id;sendRoom(r);return}
 if(m.type==='teamNames'){if(r.started||authorityLevel(r,me)<4)return;const a=safeText(m.A||'Team A',24)||'Team A',b=safeText(m.B||'Team B',24)||'Team B';r.teamNames={A:a,B:b};sendRoom(r);broadcastRoomList();return}
 if(m.type==='role'){if(r.started||authorityLevel(r,me)<4)return;const pid=String(m.playerId||''),role=String(m.role||'').toLowerCase();const target=r.players.find(p=>p.id===pid);if(!target)return;if(!['referee','commentator','official','player'].includes(role))return;if(target.id===me.id&&r.roomAdminId!==me.id)return;if(role==='player'){target.role=null;if(!target.team){const ca=teamPlayers(r,'A').length,cb=teamPlayers(r,'B').length;target.team=ca<=cb&&ca<15?'A':(cb<15?'B':'A')}if(r.refereeId===target.id)r.refereeId=null;if(r.commentatorId===target.id)r.commentatorId=null;r.officialIds.delete(target.id)}else{target.role=role;target.ready=false;if(role==='referee'){if(r.refereeId&&r.refereeId!==target.id){const old=r.players.find(p=>p.id===r.refereeId);if(old)old.role=null}r.refereeId=target.id;target.team=null}else if(role==='commentator'){if(r.commentatorId&&r.commentatorId!==target.id){const old=r.players.find(p=>p.id===r.commentatorId);if(old)old.role=null}r.commentatorId=target.id;target.team=null}else{r.officialIds.add(target.id);target.team=null}}sendRoom(r);broadcastRoomList();return}
 if(m.type==='kick'||m.type==='ban'){if(r.started||authorityLevel(r,me)<4)return;const pid=String(m.playerId||'');const target=r.players.find(p=>p.id===pid);if(!target||target.id===me.id)return;if(m.type==='ban')r.banList.add(target.name.toLowerCase());send(target.ws,{type:'kicked',message:m.type==='ban'?'You were banned from this room.':'You were kicked from this room.'});try{target.ws.close()}catch(_){};r.players=r.players.filter(p=>p.id!==target.id);assignCaptains(r);sendRoom(r);broadcastRoomList();return}
 if(m.type==='switchActive'){if(!r.started||!['playing','decision','toss'].includes(r.phase)||authorityLevel(r,me)<3)return;const pid=String(m.playerId||''),target=r.players.find(p=>p.id===pid&&p.team===m.team&&p.role==null);if(!target)return;if(m.kind==='batter'){const arr=teamPlayers(r,r.battingTeam);const ix=arr.findIndex(p=>p.id===target.id);if(ix>=0)r.batterPos=ix;}else if(m.kind==='bowler'){const arr=teamPlayers(r,r.bowlingTeam);const ix=arr.findIndex(p=>p.id===target.id);if(ix>=0)r.bowlerPos=ix;}r.commentary=`🔄 ${me.name} switched ${m.kind} to ${target.name}.`;broadcastState(r);return}
 if(m.type==='publicQuestion'){if(!r.started||!canManage(r,me))return;const text=safeText(m.text,220);if(text)broadcast(r,{type:'question',name:me.name,team:me.team,text,at:Date.now()});return}
 if(m.type==='ready'){me.ready=!me.ready;sendRoom(r);broadcastRoomList();return}
 if(m.type==='start'){if(r.started)return;if(r.roomAdminId!==me.id)return send(ws,{type:'error',message:'Only the room creator can start the match.'});const before=r.started;start(r);if(!before&&!r.started)return send(ws,{type:'error',message:'Assign at least one player to Team A and one player to Team B before starting.'});return}
 if(m.type==='tossCall'){if(!r.started||r.phase!=='toss'||!isReferee(r,me))return;const call=String(m.call||'').toLowerCase();if(call!=='heads'&&call!=='tails')return send(ws,{type:'error',message:'Choose Heads or Tails.'});r.toss=Math.random()<.5?'heads':'tails';const active=r.players.filter(p=>!p.role&& (p.team==='A'||p.team==='B'));r.tossWinner=(call===r.toss)?me.id:active.find(p=>p.id!==me.id)?.id;if(!r.tossWinner)return send(ws,{type:'error',message:'Need at least two playing players for toss.'});r.commentary=`🪙 Coin landed on ${r.toss.toUpperCase()}. ${r.players.find(p=>p.id===r.tossWinner).name} won the toss.`;r.phase='decision';broadcastState(r);return}
 if(m.type==='decision'){if(!r.started||r.phase!=='decision'||me.id!==r.tossWinner)return;const d=String(m.decision||'').toLowerCase();if(d!=='bat'&&d!=='bowl')return;const winner=r.players.find(p=>p.id===r.tossWinner);r.battingTeam=d==='bat'?winner.team:(winner.team==='A'?'B':'A');r.bowlingTeam=r.battingTeam==='A'?'B':'A';r.decision=d;r.phase='playing';r.commentary=`🏏 Team ${r.battingTeam} bats first. Active players will rotate ball-by-ball.`;broadcastState(r);return}
 if(m.type==='choice'){if(!r.started||r.phase!=='playing'||r.gameOver)return;if(Date.now()<r.lockedUntil)return send(ws,{type:'error',message:'Wait for the next ball.'});const bat=teamPlayers(r,r.battingTeam),bowl=teamPlayers(r,r.bowlingTeam);while(bat.length&&bat[r.batterPos%bat.length]?.online===false)r.batterPos++;while(bowl.length&&bowl[r.bowlerPos%bowl.length]?.online===false)r.bowlerPos++;const activeBat=bat[r.batterPos%Math.max(1,bat.length)],activeBowl=bowl[r.bowlerPos%Math.max(1,bowl.length)];if(me.id!==activeBat?.id&&me.id!==activeBowl?.id)return send(ws,{type:'error',message:'You are spectating. Wait for your turn.'});if(!Number.isInteger(m.choice)||m.choice<0||m.choice>6)return send(ws,{type:'error',message:'Choice must be 0-6.'});if(r.choices.has(me.id))return; r.choices.set(me.id,m.choice);broadcastState(r);resolve(r);return}
 if(m.type==='leave'){r.players=r.players.filter(p=>p.ws!==ws);if(!r.players.length)rooms.delete(r.code);else{r.started=false;r.phase='lobby';r.players.forEach(p=>p.ready=false);r.commentary='A player left. Match reset to lobby.';sendRoom(r);broadcastState(r)}broadcastRoomList();return}
 });
 ws.on('close',()=>{
   for(const [c,r] of rooms){
     const me=r.players.find(p=>p.ws===ws);
     if(!me) continue;
     me.online=false; me.ws=null; me.ready=false;
     if(r.roomAdminId===me.id){
       // Keep the room admin identity for reconnect. Officials/referee/captains retain their own permissions while admin is offline.
       r.commentary=`📴 ${me.name} (Room Admin) is offline. Authorized officials can manage the room.`;
     } else {
       r.commentary=`📴 ${me.name} is offline.`;
     }
     sendRoom(r); broadcastState(r); broadcastRoomList();
   }
 });
});
async function startServer(){
  try{
    const storage=await initAccountPersistence();
    server.listen(PORT,()=>console.log(`Hand Cricket Arena multiplayer server running on port ${PORT} | account storage: ${storage}`));
  }catch(e){
    console.error('FATAL: PostgreSQL account storage could not be initialized:',e.message);
    process.exit(1);
  }
}
startServer();
